### ISSUE TITLE
Github action to parse yml files

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/WELA#5]
I was first thinking of having the user download the detection rules from `hayabusa-rules` and dynamically parsing it but it will probably be slow with PwSh so it would be better to have a daily github action to download the latest rules and parse out just the needed information. This also has the benefit in that there will be no false positives from Windows Defender, etc... because we do not need to include the detection logic portion.

Since we are focusing on only `Security` logs at the moment we will parse through all the detection rules looking for `service: security`

Ex:
```
logsource:
    product: windows
    service: security
```
logs and parse out the `EventID`s being used. Then we can create a file with the following information: `<title>, <description>, <level>, <subcategory GUID>`

Example:
```
title: DiagTrackEoP Default Login Username
id: 2111118f-7e46-4fc8-974a-59fd8ec95196
status: test
description: Detects the default "UserName" used by the DiagTrackEoP POC
references:
    - https://github.com/Wh04m1001/DiagTrackEoP/blob/3a2fc99c9700623eb7dc7d4b5f314fd9ce5ef51f/main.cpp#L46
author: Nasreddine Bencherchali (Nextron Systems)
date: 2022-08-03
tags:
    - attack.privilege-escalation
logsource:
    product: windows
    service: security
detection:
    selection:
        EventID: 4624
        LogonType: 9
        TargetOutboundUserName: 'thisisnotvaliduser'
    condition: selection
falsepositives:
    - Unlikely
level: critical
```

will result in the following JSON: 
```
{
    "title": "DiagTrackEoP Default Login Username", 
    "description": "Detects the default \"UserName\" used by the DiagTrackEoP POC", 
    "level": "critical", 
    "subcategory_id": ["0CCE9215-69AE-11D9-BED3-505054503030"]
}
```

> Note: since a rule can use multiple event IDs, we need to make `subcategory_id` an array to handle multiple values. Also need to escape double quotes and handle multi-line in the `description`.

EventID to `subcategory_id` mapping will be done with the `config/eid_subcategory_mapping.txt` file.

We can save this file to `config/security_rules.json`
